CREATE DATABASE TRANSPORTE;
GO
USE TRANSPORTE;
GO


CREATE TABLE DIRECCIONES (
ID_DIRECCION INTEGER IDENTITY(1,1) PRIMARY KEY,
DEPARTAMENTO VARCHAR(25),
MUNICIPIO VARCHAR(25),
CIUDAD VARCHAR(25),
DESCRIPCION VARCHAR(50));
GO

CREATE TABLE COLORES(
ID_COLORES INTEGER IDENTITY(1,1) PRIMARY KEY,
COLOR VARCHAR(15));
GO

CREATE TABLE NUM_RODAJES(
ID_NUM_RODAJE INTEGER IDENTITY(1,1) PRIMARY KEY,
NUM_RODAJE INT NOT NULL );
GO

CREATE TABLE HORARIOS(
ID_HORARIO INT IDENTITY(1,1) PRIMARY KEY,
HORA_ENTRADA TIME NOT NULL,
HORA_SALIDA TIME NOT NULL);
GO

CREATE TABLE PARADAS (
ID_PARADA INT IDENTITY(1,1) PRIMARY KEY,
PARADA_PARTIDA VARCHAR(50) NOT NULL,
PARADA_DESTINO VARCHAR(50) NOT NULL );
GO

CREATE TABLE TAMANIOS_BUS (
ID_TAMANIO_BUS INT IDENTITY(1,1) PRIMARY KEY,
TAMANIO_BUS VARCHAR(20) NOT NULL);
GO

CREATE TABLE COMODIDADES_BUS (
ID_COMODIDAD_BUS INT IDENTITY(1,1) PRIMARY KEY,
COMODIDAD_BUS VARCHAR(20) NOT NULL);
GO

CREATE TABLE ESTADOS_BUS (
ID_ESTADO_BUS INT IDENTITY(1,1) PRIMARY KEY,
ESTADO_BUS VARCHAR(15) NOT NULL );
GO

CREATE TABLE TIPOS_LICENCIA (
ID_TIPO_LICENCIA INT IDENTITY(1,1) PRIMARY KEY,
TIPO_LICENCIA VARCHAR(15) NOT NULL,
);
GO

CREATE TABLE EMPRESAS (
ID_EMPRESA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_EMPRESA VARCHAR(50) NOT NULL,
LOGO_EMPRESA IMAGE,
ID_DIRECCION INT NOT NULL,
FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES(ID_DIRECCION)
);
GO

CREATE TABLE TIPOS_BUS (
ID_TIPO_BUS INT IDENTITY(1,1) PRIMARY KEY,
ID_TAMANIO INT NOT NULL,
ID_COMODIDAD INT NOT NULL,
ID_ESTADO INT NOT NULL,
TAFIFA DECIMAL(2,2) NOT NULL,
FOREIGN KEY (ID_TAMANIO) REFERENCES TAMANIOS_BUS(ID_TAMANIO_BUS),
FOREIGN KEY (ID_COMODIDAD) REFERENCES COMODIDADES_BUS(ID_COMODIDAD_BUS),
FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS_BUS(ID_ESTADO_BUS)
);
GO

CREATE TABLE RUTAS (
ID_RUTA INT IDENTITY(1,1) PRIMARY KEY,
LUGAR_PARTIDA VARCHAR(100) NOT NULL,
LUGAR_DESTINO VARCHAR(100) NOT NULL,
CANTIDAD_PARADAS INT NOT NULL,
ID_PARADA INT NOT NULL,
TIEMPO_VIAJE TIME NOT NULL,
PRECIO FLOAT NOT NULL,
FOREIGN KEY (ID_PARADA) REFERENCES PARADAS(ID_PARADA)
);
GO

CREATE TABLE PEAJES (
ID_PEAJE INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PEAJE VARCHAR(50) NOT NULL,
PRECIO_PAGA FLOAT NOT NULL,
ID_NUM_RODAJE INT NOT NULL,
FOREIGN KEY (ID_NUM_RODAJE) REFERENCES NUM_RODAJES(ID_NUM_RODAJE)
);
GO

CREATE TABLE RUTAS_PEAJES (
ID_RUTA_PEAJE INT IDENTITY(1,1) PRIMARY KEY,
ID_RUTA INT NOT NULL,
ID_PEAJE INT NOT NULL,
FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA),
FOREIGN KEY (ID_PEAJE) REFERENCES PEAJES(ID_PEAJE)
);
GO

CREATE TABLE LICENCIAS (
ID_LICENCIA INT IDENTITY(1,1) PRIMARY KEY,
FECHA_VENCIMIENTO DATE NOT NULL,
ID_TIPO_LICENCIA INT NOT NULL,
TIPO_SANGRE VARCHAR(5) NOT NULL,
FECHA_EMISION DATE NOT NULL,
FOREIGN KEY (ID_TIPO_LICENCIA) REFERENCES TIPOS_LICENCIA(ID_TIPO_LICENCIA)
);
GO

CREATE TABLE DATOS_PERSONAS (
ID_DATOS_PERSONA INT IDENTITY(1,1) PRIMARY KEY,
PRIMER_NOMBRE VARCHAR(20) NOT NULL,
SEGUNDO_NOMBRE VARCHAR(20),
PRIMER_APELLIDO VARCHAR(20) NOT NULL,
SEGUNDO_APELLIDO VARCHAR(20),
NO_IDENTIDAD VARCHAR(15) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
GENERO VARCHAR(1) NOT NULL,
ESTADO_CIVIL VARCHAR(25) NOT NULL,
FOTOGRAFIA IMAGE,
ID_DIRECCION INT NOT NULL,
FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES(ID_DIRECCION)
);
GO

CREATE TABLE SOCIOS(
ID_SOCIO INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_PERSONA INT NOT NULL,
ESTADO BIT NOT NULL,
FOREIGN KEY (ID_DATOS_PERSONA) REFERENCES DATOS_PERSONAS(ID_DATOS_PERSONA)
);
GO

CREATE TABLE EMPRESA_SOCIOS (
ID_EMPRESA_SOCIO INT IDENTITY(1,1) PRIMARY KEY,
ID_EMPRESA INT NOT NULL,
ID_SOCIO INT NOT NULL,
FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA),
FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS(ID_SOCIO)
);
GO

CREATE TABLE PASAJEROS (
ID_PASAJERO	 INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_PERSONA INT NOT NULL,
CORREO VARCHAR(50) NOT NULL,
FOREIGN KEY (ID_DATOS_PERSONA) REFERENCES DATOS_PERSONAS(ID_DATOS_PERSONA)
);
GO

CREATE TABLE SOCIOS_TELEFONOS (
ID_SOCIOS_TELEFONO	 INT IDENTITY(1,1) PRIMARY KEY,
ID_SOCIO INT NOT NULL,
TELEFONO VARCHAR(12) NOT NULL,
FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS(ID_SOCIO)
);
GO

CREATE TABLE DATOS_EMPLEADOS (
ID_DATOS_EMPLEADO INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_PERSONA INT NOT NULL,
CONTRASENIA VARBINARY(max) NOT NULL,
ID_HORARIO INT NOT NULL,
SUELDO FLOAT NOT NULL,
FOREIGN KEY (ID_HORARIO) REFERENCES HORARIOS(ID_HORARIO),
FOREIGN KEY (ID_DATOS_PERSONA) REFERENCES DATOS_PERSONAS(ID_DATOS_PERSONA)
);
GO

CREATE TABLE GUARDIAS (
ID_GUARDIA INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_EMPLEADO INT NOT NULL,
NOMBRE_EMPRESA_SEGURIDAD VARCHAR(50) NOT NULL,
FOREIGN KEY (ID_DATOS_EMPLEADO) REFERENCES DATOS_EMPLEADOS(ID_DATOS_EMPLEADO)
);
GO

CREATE TABLE CONDUCTORES (
ID_CONDUCTOR INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_EMPLEADO INT NOT NULL,
ACTIVO BIT NOT NULL,
FOREIGN KEY (ID_DATOS_EMPLEADO) REFERENCES DATOS_EMPLEADOS(ID_DATOS_EMPLEADO)
);
GO

CREATE TABLE ASISTENTES_CONDUCTOR (
ID_ASISTENTE_CONDUCTOR INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_EMPLEADO INT NOT NULL,
NUM_ASISTENTE INT NOT NULL,
FOREIGN KEY (ID_DATOS_EMPLEADO) REFERENCES DATOS_EMPLEADOS(ID_DATOS_EMPLEADO)
);
GO

CREATE TABLE ATENCION_PASAJEROS (
ID_ATENCION_PASAJERO INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_EMPLEADO INT NOT NULL,
NUM_VENTANILLA INT NOT NULL,
FOREIGN KEY (ID_DATOS_EMPLEADO) REFERENCES DATOS_EMPLEADOS(ID_DATOS_EMPLEADO)
);
GO

CREATE TABLE SUCURSALES (
ID_SUCURSAL INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_SUCURSAL VARCHAR(50) NOT NULL,
ID_DIRECCION INT NOT NULL,
ID_EMPRESA_PERTENECE INT NOT NULL,
ID_NOMBRE_ENCARGADO INT NOT NULL,
ID_HORARIO INT NOT NULL,
CANTIDAD_BUSES_SUCURSAL INT NOT NULL,
DIAS_ATENCION VARCHAR(100) NOT NULL,
FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES(ID_DIRECCION),
FOREIGN KEY (ID_EMPRESA_PERTENECE) REFERENCES EMPRESAS(ID_EMPRESA),
FOREIGN KEY (ID_NOMBRE_ENCARGADO) REFERENCES DATOS_PERSONAS(ID_DATOS_PERSONA),
FOREIGN KEY (ID_HORARIO) REFERENCES HORARIOS(ID_HORARIO)
);
GO

CREATE TABLE SUCURSAL_TELEFONOS (
ID_SUCURSAL_TELEFONO INT IDENTITY(1,1) PRIMARY KEY,
ID_SUCURSAL INT NOT NULL,
TELEFONO VARCHAR(12) NOT NULL,
FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL)
);
GO

CREATE TABLE SUCURSAL_RUTAS (
ID_SUCURSAL_RUTA INT IDENTITY(1,1) PRIMARY KEY,
ID_SUCURSAL INT NOT NULL,
ID_RUTA INT NOT NULL,
FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL),
FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA)
);
GO

CREATE TABLE LICENCIA_CONDUCTORES (
ID_LICENCIA_CONDUCTOR INT IDENTITY(1,1) PRIMARY KEY,
ID_LICENCIA INT NOT NULL,
ID_CONDUCTOR INT NOT NULL,
FOREIGN KEY (ID_LICENCIA) REFERENCES LICENCIAS(ID_LICENCIA),
FOREIGN KEY (ID_CONDUCTOR) REFERENCES CONDUCTORES(ID_CONDUCTOR)
);
GO

CREATE TABLE OTROS_EMPLEADOS (
ID_OTRO_EMPLEADO INT IDENTITY(1,1) PRIMARY KEY,
ID_SUCURSAL INT NOT NULL,
ID_DATOS_EMPLEADO INT NOT NULL,
CATEGORIA VARCHAR(20) NOT NULL,
FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL),
FOREIGN KEY (ID_DATOS_EMPLEADO) REFERENCES DATOS_EMPLEADOS(ID_DATOS_EMPLEADO)
);
GO

CREATE TABLE BUSES (
ID_BUS INT IDENTITY(1,1) PRIMARY KEY,
MODELO VARCHAR(30) NOT NULL,
SERIE VARCHAR(30) NOT NULL,
NO_MATRICULA VARCHAR(12) NOT NULL,
NO_PLACA VARCHAR(12) NOT NULL,
PRECIO_MATRICULA FLOAT NOT NULL,
CAPACIDAD_CARGA FLOAT NOT NULL,
ESTADO_MATRICULA BIT NOT NULL,
CAPACIDAD_PASAJEROS INT NOT NULL,
ID_ESTADO INT NOT NULL,
ID_RUTA_ASIGNADO INT NOT NULL,
ID_CONDUCTOR_ASIGNADO INT NOT NULL,
ID_ASISTENTE_CONDUCTOR INT NOT NULL,
ID_TIPO_BUS INT NOT NULL,
ID_SUCURSAL INT NOT NULL,
FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS_BUS(ID_ESTADO_BUS),
FOREIGN KEY (ID_RUTA_ASIGNADO) REFERENCES RUTAS(ID_RUTA),
FOREIGN KEY (ID_CONDUCTOR_ASIGNADO) REFERENCES CONDUCTORES(ID_CONDUCTOR),
FOREIGN KEY (ID_ASISTENTE_CONDUCTOR) REFERENCES ASISTENTES_CONDUCTOR(ID_ASISTENTE_CONDUCTOR),
FOREIGN KEY (ID_TIPO_BUS) REFERENCES TIPOS_BUS(ID_TIPO_BUS),
FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL)
);
GO

CREATE TABLE OBSERVACIONES_DATOS_EMPLEADO (
ID_OBSERVACION_DATOS_EMPLEADO INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_EMPLEADO INT NOT NULL,
OBSERVACION VARCHAR(250) NOT NULL,
FECHA DATE NOT NULL,
FOREIGN KEY (ID_DATOS_EMPLEADO) REFERENCES DATOS_EMPLEADOS(ID_DATOS_EMPLEADO)
);
GO

CREATE TABLE BOLETOS (
ID_BOLETO INT IDENTITY(1,1) PRIMARY KEY,
NUM_BOLETO INT NOT NULL,
ID_BUS INT NOT NULL,
ID_RUTA INT NOT NULL,
ID_TIPO_BUS INT NOT NULL,
VIGENCIA BIT NOT NULL,
COSTO_BOLETO FLOAT NOT NULL,
FOREIGN KEY (ID_BUS) REFERENCES BUSES(ID_BUS),
FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA),
FOREIGN KEY (ID_TIPO_BUS) REFERENCES TIPOS_BUS(ID_TIPO_BUS)
);
GO

CREATE TABLE BOLETOS_PASAJEROS (
ID_BOLETOS_PASAJERO INT IDENTITY(1,1) PRIMARY KEY,
ID_BOLETO INT NOT NULL,
ID_PASAJERO INT NOT NULL,
FOREIGN KEY (ID_BOLETO) REFERENCES BOLETOS(ID_BOLETO),
FOREIGN KEY (ID_PASAJERO) REFERENCES PASAJEROS(ID_PASAJERO)
);
GO

CREATE TABLE BUSES_COLORES (
ID_BUS_COLORES INT IDENTITY(1,1) PRIMARY KEY,
ID_BUS INT NOT NULL,
ID_COLOR INT NOT NULL,
FOREIGN KEY (ID_BUS) REFERENCES BUSES(ID_BUS),
FOREIGN KEY (ID_COLOR) REFERENCES COLORES(ID_COLORES)
);
GO

CREATE TABLE EMPRESAS_BUSES (
ID_EMPRESA_BUSES INT IDENTITY(1,1) PRIMARY KEY,
ID_EMPRESA INT NOT NULL,
ID_BUS INT NOT NULL,
FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA),
FOREIGN KEY (ID_BUS) REFERENCES BUSES(ID_BUS)
);
GO

CREATE TABLE CORREOS_DATOS_EMPLEADOS (
ID_CORREO_DATOS_EMPLEADO INT IDENTITY(1,1) PRIMARY KEY,
ID_DATOS_EMPLEADO INT NOT NULL,
CORREO VARCHAR(50) NOT NULL,
FOREIGN KEY (ID_DATOS_EMPLEADO) REFERENCES DATOS_EMPLEADOS(ID_DATOS_EMPLEADO),
CONSTRAINT UC_CORREOS_DATOS_EMPLEADOS UNIQUE (ID_DATOS_EMPLEADO,CORREO)
);
GO



